# Generated by Django 3.2.8 on 2021-11-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=250)),
                ('job_role', models.CharField(max_length=200)),
                ('working_in_us_shift', models.BooleanField(default=False)),
                ('notice_period', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
